### ISSUE TITLE
Modular Magic TileGridProvider crash in 1.6.0

### ISSUE THREAD

**Issue by Regnaur** [Frinn38/Modular-Magic#11]
[crash-2020-04-24_21.24.22-client.txt](https://github.com/Frinn38/Modular-Magic/files/4532354/crash-2020-04-24_21.24.22-client.txt)

Seems to be XU2 integration?

**Comment by Regnaur** [comment]
might be related to #10

**Comment by Regnaur** [comment]
also happens with just Modular Magic, MM, and XU2
[crash-2020-04-24_22.25.23-client.txt](https://github.com/Frinn38/Modular-Magic/files/4532405/crash-2020-04-24_22.25.23-client.txt)

**Comment by Frinn38** [comment]
Yeah, same crash with XU2, Thaumcraft and even Astral Sorcery, now this is fixed.
