### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Xaikii** [Frinn38/Modular-Magic#13]
https://pastebin.com/Z34PTLSp

Forge: 14.23.5.2847
Modular Magic: 1.6.2
Modular Machinery: 1.12.2-1.10.0
Astral Sorcery: 1.12.2-1.10.23
Blood Magic: 1.12.2-2.4.3-105
Thaumcraft: 1.12.2-6.1.BETA26
Extra Utils: 1.12-1.9.9
Botania: r1.10-363

**Comment by Frinn38** [comment]
Update Modular Machinery, 1.5+ versions of Modular Magic are only compatible with MM 1.11+

**Comment by Xaikii** [comment]
sry for the late response, been a bit busy

thanks for the response, I thought I've been on the latest, and noticed also why I wasn't (Modular Diversity), everything works

Is there a chance you're adding the TC Aura or Embers Stuff (but I assume Embers would rather count as Tech)

**Comment by Frinn38** [comment]
Nope, sorry but I don't code on 1.12 anymore as this version is dead.
I added Botania support only because someone PR the code for it, you can do the same if you want another mod support.
