### ISSUE TITLE
[bug]Life Essence Output Hatch cause the game to crashc

### ISSUE THREAD

**Issue by bakahdt** [Frinn38/Modular-Magic#19]
I use version 1.4.0 Modular_Magic built a machine to input energy and output Life_Essence. When I put the Blood Orb into the output hatch, the machine worked normally. But once I took the Blood Orb out, the game would crash and the world would be damaged.Later, I updated the latest version, but it would crash when I started the game.

This is my crash report when I took out blood orb: https://paste.ubuntu.com/p/QXKdwvmWSm/

This is an crash report when I installed the new version of Modular_Magic: https://paste.ubuntu.com/p/J29gC2mbSc/

I can't speak English, so I used the translation software. I hope you can forgive me

**Comment by Frinn38** [comment]
You need the latest version of Modular Machinery to use Modular Magic 1.5.0+ but then Modular Diversity will not be compatible and will crash the game, so you can either drop MD or use Modular Magic 1.4.0 but not have the latest features and bugfixes.
