### ISSUE TITLE
[suggestion] botania, embers support?

### ISSUE THREAD

**Issue by tlitookilakin** [Frinn38/Modular-Magic#2]
is this possible? it would be cool to be able to make machines that require mana or embers to run.

**Comment by Frinn38** [comment]
Well it is possible and it already exist in [Modular Diversity](https://minecraft.curseforge.com/projects/modular-diversity) so I will not add it in this mod.

**Comment by tlitookilakin** [comment]
Oh, didn't know that mod was a thing! thank you.
