### ISSUE TITLE
[Suggestion] CraftTweaker Support

### ISSUE THREAD

**Issue by MrTK-Dev** [Frinn38/Modular-Magic#3]
Hey,
what about adding CraftTweaker support?
Thank you for creating this mod!

**Comment by Frinn38** [comment]
Planned !
I will focus on it after finishing the integration of astral sorcery

**Comment by Frinn38** [comment]
Added in 1.5 !
Wiki will be updated soon, but you can find all the crafttweaker methods [here](https://github.com/Frinn38/Modular-Magic/blob/master/src/main/java/fr/frinn/modularmagic/common/integration/crafttweaker/MagicPrimer.java) for now (it works the same as Modular Machinery and Diversity)
