### ISSUE TITLE
[1.5.0] Some issues I found while playing around with your mod.

### ISSUE THREAD

**Issue by wamc2017** [Frinn38/Modular-Magic#4]
Hi,

I played around with your mod a little bit and found some issues.
First of, the versions I'm using:
Minecraft: 1.12.2
Forge: 14.23.5.2838
Modular Magic: 1.5.0
Modular Machinery: 1.11.1

1. The first error I encountered while adding recipes for demon will, essentia and constellations:
https://gist.github.com/wamc2017/35e3777c4adab9272832e9c92ef45470

To fix this error I changed:

https://github.com/Frinn38/Modular-Magic/blob/855e5d324bd7517235975b44f8bd76365844a42a/src/main/java/fr/frinn/modularmagic/common/utils/RequirementUtils.java#L94

to:

`String s = json.getAsJsonPrimitive(key).getAsString();`

and recompiled the mod (don't know if this is the best way to fix this, but it worked for me...)

2. It seems only the BloodMagic blocks are changing color if the multiblock is formed:
![2019-08-14_00 50 04](https://user-images.githubusercontent.com/33242447/62989329-d65ec000-be47-11e9-81a6-96188785bb2d.png)

(I changed the default color to black to check if this is working, but after forming, they should all be white...)

3. I added an input and an output recipe for lifeessence to the same machine and if the orb is in the output and there's no valid output recipe in progress, it uses it as input. I guess this should not be the case and the network should not be drained, if the orb is in the output...

4. I don't know the mod well enough yet, so maybe I did something wrong, but the default suction of the essentia input is 32 Untyped (the same as a normal jar). Is there a way to set the type of essentia? I tried clicking on the hatch with a vis crystal, a full jar and some phials, but nothing changed the type. Also tried attaching a label...
So the only ways are to pipe something in via an essentia buffer or from an alembic, is this intended?

5. I had a crash when looking in JEI for the uses of the blueprint (seems to only happen with demon will recipes):
https://gist.github.com/wamc2017/061200e33008635898d2b36749abc1ed

Thanks for reading my report, if you need more infos, feel free to ask. :)

Cheers
wamc

**Comment by Frinn38** [comment]
First, thanks for testing this mod ;) now for the bugs : 
1. Just a missclick, fixed.

2. After some testing, it seems that the way MM set the color to the block is not compatible with some hatchs (as it would require to extends 2 classes) so for now Aspect, GP and Starlight hatchs can not be colored. I will talk with HellFirePvP to try to find an alternative.

3. LP Outut hatch was registered as input hatch... copy paste fault x) Fixed now.

4. I don't know thaumcraft either but now the essentia hatches should work as the thaumcraft does, so you can empty a phial in the hatch (or fill it from) and set a label.

5. Should be Fixed now. If it happend again give me the recipe json (or crafttweaker).

**Comment by Frinn38** [comment]
Finished to fix all of this in 1.6.0, now all blocks are coloring and the essentia hatches can be labeled like the thaumcraft jar.
