### ISSUE TITLE
[1.5.1] Crash on start if both Astral Sorcery and Thaumcraft are not present.

### ISSUE THREAD

**Issue by stingerbrg** [Frinn38/Modular-Magic#8]
When starting up Minecraft the game will not load if both Astral and Thaumcraft aren't present.  If they are both there it loads up fine, it doesn't matter if the other mods Modular Magic is compatible with are there or not.  No machines or recipes added yet.  All versions are the most recent.  

Crash report for when neither Astral and Thaumcraft are present:
https://paste.dimdev.org/ixubamigip.mccrash

Crash report for when Astral is present but not Thaumcraft:
https://paste.dimdev.org/ujesiboziq.mccrash

Crash report for when Thaumcraft is present but not Astral:
https://paste.dimdev.org/uxecehijez.mccrash

If I change to Modular Magic 1.5.0 it loads up fine without Thaumcraft, but still crashes without Astral.

**Comment by Frinn38** [comment]
Fixed in 1.6.0 !
